// TypeScript declaration stubs for Vite PWA virtual modules.
// This quiets “Cannot find module 'virtual:pwa-register'” errors coming from main.tsx.

declare module "virtual:pwa-register" {
  export interface RegisterSWOptions {
    immediate?: boolean;
    onOfflineReady?: () => void;
    onNeedRefresh?: () => void;
  }

  /**
   * Registers the service worker generated by @vite-pwa/vite-plugin.
   * Returns a function that can be called to manually trigger an update check.
   */
  export function registerSW(
    options?: RegisterSWOptions,
  ): (reloadPage?: boolean) => void;
}

declare module "virtual:pwa-register/*" {
  export * from "virtual:pwa-register";
}
